### ISSUE TITLE
node update 에러

### ISSUE THREAD

**Issue by kimjayney** [6-6/CloudMind#40]
현재 노드 업데이트 부분에서 전체적으로 에러가 발생하는듯 합니다.

주소는 http://localhost:8080/api/v1/node/update 이고

노드 ModalView 에서 값을 변경하려 할때

{"node_idx":4,"node_name":"dsfsdf","description":"dsfsdf","due_date":null}

다음과 같은 payload 값을 보내면 500 코드와 함께 에러 메세지가 발생합니다.

또한 할당된 인원을 추가하려 할때도 에러가 발생하여서, 아마 내부 처리에서 문제가 생기는것 같습니다

**Comment by vbalien** [comment]
assigned_users 필드는 반드시 있어야 합니다.
유저 인덱스 리스트( [1, 2, 4, 6] 식으로... )로 넘겨주시고 에러메시지 알려주세요.

**Comment by kimjayney** [comment]
[노드 description 수정]

POST http://localhost:8080/api/v1/node/update 

Payload : {"node_idx":4,"node_name":"test","description":"sdfsdfsd","due_date":null}

<Response>

builtins.AttributeError

AttributeError: 'NoneType' object has no attribute 'read'

Traceback (most recent call last)

File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in **call**

return self.wsgi_app(environ, start_response)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app

response = self.make_response(self.handle_exception(e))
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/**init**.py", line 270, in error_router

return original_handler(e)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception

reraise(exc_type, exc_value, tb)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise

raise value.with_traceback(tb)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app

response = self.full_dispatch_request()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request

rv = self.handle_user_exception(e)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/**init**.py", line 270, in error_router

return original_handler(e)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception

reraise(exc_type, exc_value, tb)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise

raise value.with_traceback(tb)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request

rv = self.dispatch_request()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/**init**.py", line 471, in wrapper

resp = resource(_args, *_kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view

return self.dispatch_request(_args, *_kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/**init**.py", line 581, in dispatch_request

resp = meth(_args, *_kwargs)
File "/Users/rainc/SoMa2/CloudMind/cloudmind/restful/v1/node.py", line 138, in post

due_date = date_parser.parse(args['due_date'])
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dateutil/parser.py", line 1008, in parse

return DEFAULTPARSER.parse(timestr, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dateutil/parser.py", line 392, in parse

res = self._parse(timestr, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dateutil/parser.py", line 492, in _parse

l = _timelex.split(timestr)         # Splits the timestr into tokens
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dateutil/parser.py", line 174, in split

return list(cls(s))
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dateutil/parser.py", line 164, in **next**

token = self.get_token()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dateutil/parser.py", line 82, in get_token

nextchar = self.instream.read(1)
AttributeError: 'NoneType' object has no attribute 'read'

[캘린더에서 노드 날짜 변경]

POST http://localhost:8080/api/v1/node/update

Payload : {"node_idx":3,"node_name":"IDC","description":null,"due_date":"2015-11-11"}

builtins.KeyError

<Response>

KeyError: 'assigned_users'

Traceback (most recent call last)

File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1836, in **call**

return self.wsgi_app(environ, start_response)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app

response = self.make_response(self.handle_exception(e))
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/**init**.py", line 270, in error_router

return original_handler(e)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception

reraise(exc_type, exc_value, tb)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise

raise value.with_traceback(tb)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app

response = self.full_dispatch_request()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request

rv = self.handle_user_exception(e)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/**init**.py", line 270, in error_router

return original_handler(e)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception

reraise(exc_type, exc_value, tb)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise

raise value.with_traceback(tb)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request

rv = self.dispatch_request()
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/**init**.py", line 471, in wrapper

resp = resource(_args, *_kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask/views.py", line 84, in view

return self.dispatch_request(_args, *_kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_restful/**init**.py", line 581, in dispatch_request

resp = meth(_args, *_kwargs)
File "/Users/rainc/SoMa2/CloudMind/cloudmind/restful/v1/node.py", line 139, in post

users = args['assigned_users']
KeyError: 'assigned_users'
This is the Copy/Paste friendly version of the traceback. You can also paste this traceback into a gist:  create paste
