### ISSUE TITLE
프로젝트 리스트에서 프로젝트 클릭 시 노드의 위치가 제대로 지정되지 않는 이슈

### ISSUE THREAD

**Issue by kimjayney** [6-6/CloudMind#43]
TypeError: Cannot read property 'attachChild' of undefined 에러가 발생

에러 메세지 

TypeError: Cannot read property 'attachChild' of undefined
    at Object.SceneGraph.appendNode (http://localhost:8080/js/app/mindmap/mindmap_controller.js:49:28)
    at new <anonymous> (http://localhost:8080/js/app/mindmap/mindmap_controller.js:95:21)
    at Object.invoke (http://localhost:8080/libs/angular/angular/angular.js:4450:17)
    at extend.instance (http://localhost:8080/libs/angular/angular/angular.js:8999:34)
    at nodeLinkFn (http://localhost:8080/libs/angular/angular/angular.js:8109:36)
    at compositeLinkFn (http://localhost:8080/libs/angular/angular/angular.js:7541:13)
    at publicLinkFn (http://localhost:8080/libs/angular/angular/angular.js:7416:30)
    at http://localhost:8080/libs/angular/angular-ui-router/release/angular-ui-router.js:4026:9
    at invokeLinkFn (http://localhost:8080/libs/angular/angular/angular.js:8650:9)
    at nodeLinkFn (http://localhost:8080/libs/angular/angular/angular.js:8150:11) <div class="app-content-body ng-scope" ui-view="" data-ng-animate="1">

**Comment by kimjayney** [comment]
{
    "node_list": [
        {
            "assigned_users": [
                1
            ],
            "creation_date": "2015-11-12T04:38:04.061388",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-11T00:00:00",
            "labels": [],
            "leafs": [],
            "name": "IDC",
            "node_idx": 3,
            "parent_idx": null,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-12T05:22:15.076258",
            "labels": [],
            "leafs": [],
            "name": "\u314a\u314a",
            "node_idx": 5,
            "parent_idx": 3,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-12T00:00:00",
            "labels": [],
            "leafs": [],
            "name": "sfsdf",
            "node_idx": 6,
            "parent_idx": 3,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-12T05:22:15.076258",
            "labels": [],
            "leafs": [],
            "name": "sdfsdf",
            "node_idx": 7,
            "parent_idx": 6,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-12T05:22:15.076258",
            "labels": [],
            "leafs": [],
            "name": "sdfds",
            "node_idx": 8,
            "parent_idx": 6,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-18T00:00:00",
            "labels": [],
            "leafs": [],
            "name": "sdfsdf",
            "node_idx": 9,
            "parent_idx": 6,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-11T00:00:00",
            "labels": [],
            "leafs": [],
            "name": "sdfdsf",
            "node_idx": 10,
            "parent_idx": 6,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-14T00:00:00",
            "labels": [],
            "leafs": [],
            "name": "sdfsdf",
            "node_idx": 11,
            "parent_idx": 6,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-12T05:22:15.076258",
            "labels": [],
            "leafs": [],
            "name": "\u3134\u3147\u3139\u3147\u3134\u3139\u3134",
            "node_idx": 12,
            "parent_idx": 5,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-11T00:00:00",
            "labels": [],
            "leafs": [],
            "name": "\ud760",
            "node_idx": 13,
            "parent_idx": 5,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-10T00:00:00",
            "labels": [],
            "leafs": [],
            "name": "\ud750\uc544\uc554",
            "node_idx": 14,
            "parent_idx": 5,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-10T00:00:00",
            "labels": [],
            "leafs": [],
            "name": "\ud750\uc544\uc544\u314f\u3147\u3141",
            "node_idx": 15,
            "parent_idx": 5,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T05:22:15.076227",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-13T00:00:00",
            "labels": [],
            "leafs": [],
            "name": "\ud750\uc544\uc554",
            "node_idx": 16,
            "parent_idx": 5,
            "root_idx": 3
        },
        {
            "assigned_users": [],
            "creation_date": "2015-11-12T14:38:53.837083",
            "creator_id": 1,
            "description": null,
            "due_date": "2015-11-12T14:38:53.837115",
            "labels": [],
            "leafs": [],
            "name": "\u3147\u3139\u3147",
            "node_idx": 18,
            "parent_idx": null,
            "root_idx": 3
        }
    ],
    "success": true
}
